### ISSUE TITLE
issue with values from pandas `read_xxx()` data frames

### ISSUE THREAD

**Issue by pohutukawa** [innobi/pantab#1]
I've just had a look at this fine project. When I threw my own testing data set at it, it choked. I've read the data set using the Pandas `pd.read_csv()` for a CSV file, or `pd.read_parquet()` for an (equivalent) Parquet file. This sample file contained some empty `string` fields, which got mapped to a `float` with value `nan` (in Pandas terms, when reading the CSV file) or a `None` (when reading the Parquet file).

Unfortunately `pantab` passed the values through to `tableausdk`'s `setString` function, it choked with an exception. I've been able to patch the `__init__.py` to work around this (for now), but I don't think it's a 'clean enough' solution. I'm just testing for the `setString` accessor in `_append_args_for_val_and_accessor`, and I'm appending `''` to `arg_l` in case of a `nan` or `None`.

If you wish, I can provide a PR with that fix. But I do think it deserves a cleaner solution.

**Comment by WillAyd** [comment]
Thanks for raising the report! It's been pretty quiet out here so good to see someone getting use out of this

Hmm OK. Yea I think everything in an object dtype is assumed to be a string, so that would fail for NA values and other non-object types as well. 

Ideally for object what we should do is mask NA values up front and explicitly cast everything else to string before writing it out. If you are up for a PR would certainly welcome that

**Comment by WillAyd** [comment]
With the new switch to the Hyper API I don't think this issue is still applicable so closing, but if you have a problem with the new API let me know and can revisit
