### ISSUE TITLE
AWS Glue -- NotImplementedError:

### ISSUE THREAD

**Issue by nickwawee** [innobi/pantab#198]
**Describe the bug**
Cannot import both tableauhyperapi and pantab within an AWS Glue Jupyter Notebook

**To Reproduce**

```python
%additional_python_modules tableauhyperapi,pantab #installs latest version of both supposedly via pip
import tableauhyperapi
import pantab
```

**Expected behavior**
Pantab can import

**Screenshots**
![image](https://github.com/innobi/pantab/assets/35239333/59d19aa3-a595-420a-b1cf-ac7a801e471c)

**Desktop (please complete the following information):**
AWS Glue Jupyter Notebook
**Additional context**
Was originally trying to reproduce an error I was receiving for writing a hyper file to an S3 bucket in AWS Glue. If/once this is fixed, will submit a separate issue.

**Comment by WillAyd** [comment]
Hi @nickwawee thanks for submitting this. Can you try installing something other than the latest tableauhyperapi version? Maybe one or two versions back?

The error suggests that the C API for the tableauhyperapi changed which is problematic for pantab.

**Comment by WillAyd** [comment]
@nickwawee any chance you tried an older version of the tableau hyper api?

**Comment by vogelsgesang** [comment]
@nickwawee Which version of pantab are you using?

I have a feeling that you are using a rather old version of pantab together with a more recent version of Hyper API. Afaict, the issue you are running into was already fixed in [this commit](https://github.com/innobi/pantab/pull/146/files#diff-c1ea8d84f84182d79e46d5c01bc859dec8f421956e25432820b814342b8c9fb3R114) over a year ago.

**Comment by WillAyd** [comment]
Closing as I don't think this is actionable. But feel free to comment back if there is
