### ISSUE TITLE
Default database version

### ISSUE THREAD

**Issue by jryan814** [innobi/pantab#331]
**Is your feature request related to a problem? Please describe.**
Yes. I love pantab, but when using the latest version (5.0) I am unable to do anything with the hyper files, because of the default database version being set to 4. According to the hyper api documentation: 
"The database file format version 4 will be supported by Tableau Desktop/Server/Prep 2024.3 and never product versions."
Meaning I can't publish them or open them with Tableau Desktop.

**Describe the solution you'd like**
A method to change the default_database_version

**Describe alternatives you've considered**
It would be fine to have the default be "3" as it applies to more versions of Tableau Desktop & Server, but being limited to the 2024.3 and newer makes this pantab version it somewhat unusable.

**Additional context**
This block of code in the write.cpp is what appears to be setting the default_database_version:
```
 const std::unordered_map<std::string, std::string> params = {
      {"log_config", ""}, {"default_database_version", "4"}};
  const hyperapi::HyperProcess hyper{
      hyperapi::Telemetry::DoNotSendUsageDataToTableau, "", std::move(params)};
```

**Comment by WillAyd** [comment]
Argh...sorry about that! The reason for the bump from 0 to 4 was because many of the new features from version 5 only work with database version 4 (single point precision being an example, and I vaguely recall parts of the Numeric/Decimal handling)

This issue has come up in the past and someone opened a PR to make this a user configuration option, though my feedback was I'd rather have a generic way to pass options through to the Hyper connection rather than hard-coding those elements into the pantab API.

You can see the PR for that here - if you have any interest in picking that up and seeing it through this would be a great addition

**Comment by WillAyd** [comment]
Forgot to include the link - https://github.com/innobi/pantab/pull/296#issuecomment-2294898070
